#
# For testing Sumatra's postgresql support
#
# based on example Dockerfile from http://docs.docker.io/en/latest/examples/postgresql_service/ by SvenDowideit@docker.com
#
# Usage:  docker build -t postgresql_test -f Dockerfile.postgres .

FROM debian:bookworm
MAINTAINER andrew.davison@cnrs.fr

RUN apt-get update
RUN apt-get -y -q install software-properties-common
RUN apt-get -y -q install postgresql-15 postgresql-client-15 postgresql-contrib-15

USER postgres
RUN    /etc/init.d/postgresql start &&\
    psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'docker';" &&\
    createdb -O docker sumatra_test

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/15/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/15/main/postgresql.conf

EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME	["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/15/bin/postgres", "-D", "/var/lib/postgresql/15/main", "-c", "config_file=/etc/postgresql/15/main/postgresql.conf"]
