#!/usr/bin/env python
"""
Command-line interface to the Sumatra simulation management tool.
"""

import sys
from sumatra import commands, __version__

modes = ("init", "configure", "info", "run", "list", "delete", "comment", "tag", "repeat")

usage = """Usage: smt <subcommand> [options] [args]
        
Simulation/analysis management tool version %s 

Available subcommands:  
  """ % __version__ 
usage += "\n  ".join(modes)

if len(sys.argv) < 2:
    print usage
    sys.exit(1)

cmd = sys.argv[1]
try:
    main = getattr(commands, cmd)
except AttributeError:
    print usage
    sys.exit(1)
    
main(sys.argv[2:])
