#!/usr/bin/env python

import sys
from sumatra import commands

modes = ("run","batch","init", "configure", "info","list","comment","tag","repeat","package","delete","runserver","debug")

usage = """Usage: smt <subcommand> [options] [args]
        
Simulation management tool, version 0.1

Available subcommands:  
  """ + "\n  ".join(modes)

if len(sys.argv) < 2:
    print usage
    sys.exit(1)

cmd = sys.argv[1]
try:
    main = getattr(commands, cmd)
except AttributeError:
    print usage
    sys.exit(1)
    
main(sys.argv[2:])