name: Run Sumatra tests on Windows

on: [push, pull_request]

jobs:

  test_minimal:  # run tests with minimal installation
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.11", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[hg,git,test]
          pip freeze
      - name: Configure git
        run: |
          git config --global user.email "testuser@example.org"
          git config --global user.name "Test user"
      - name: Test with pytest
        run: |
          pytest -v
